// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cawtawfdvogdhtsgkjdr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhd3Rhd2Zkdm9nZGh0c2dramRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNzY1NjYsImV4cCI6MjA2NjY1MjU2Nn0.IjIH0q5YqundGbM5Q-3TCH3_rK4xysCYInbR2GO73ys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);